travis:
  secure:
    BINSTAR_TOKEN: NntQS7qnbSXJ2i6pentV8/jAo7JZfS/arEP1ht7v3gnKyqcFtBGa3VlYd+yCTVQN1ZsBB4HbJJEjiMNqALH6BtigLTeV217Y7M8gYkUbvxeF6b98c7Su3ZjB8TKugrEHD+/dYDGCAQeUSm7yJAwYIXnRnqP0kGgGgpJax5nz9hA/D9gWYNKR8rpvVxgv/huaW6X3BEawashBE18N1zN8cweDwaE11A72/uLJVNJX4JMDWjaKmNkjF9CjIqD5uuOVAIecv1gdmEQnfOPQm/mibIqiARFVoB+dACO+hYL6L3Oy+DXQYLmd12jerFwUfmkZalJ7lKKNccUmUAf7SyQoMy5eAOWxP36kYWilzU8A7esp4GR0YOz662sT3ESvi1GybPEWK7Bk8s941GSd9cBP5Vh2lVKJ/uBE45xiViiUgLvq4TgSAL4n7SO4DWEFDxVZ0RONBBRIkivjIgdODNemmieZZb9sAwfIKnfo+BuU+8hsgHWxyipK8fHKsYOnAI4w85SMay2DdTjcGaWmDKJKXHSS9ygRF6hd9InONhMfwQsmfsJkOrzV+P98LW64BWOyQXqpi25+45nV2H6WGK41oDGLffs7Ow2XajvcuUk0gvUwEWjbJFtQtZ8y7ZI3TRkuhNMAInBtDBCG9bcRpQoIpH8yxxTmc77Xg6w0R/xnMjU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
