{% set version = "1.2.11" %}

package:
  name: sbcl
  version: {{ version }}

source:
  url: http://prdownloads.sourceforge.net/sbcl/sbcl-{{ version }}-x86-64-darwin-binary.tar.bz2  # [osx]
  sha256: 057d3a1c033fb53deee994c0135110636a04f92d2f88919679864214f77d0452

build:
  number: 0
  skip: true  # [win]
  skip: true  # [linux]

requirements:
  build:
  host:
  run:

test:
  commands:
    - sbcl --version
    - sbcl --help
    - sbcl --eval '(print "hello world")' --quit

about:
  home: http://www.sbcl.org
  license: BSD
  summary: Steel Bank Common Lisp (SBCL) is a high performance Common Lisp compiler
  description: |
    Steel Bank Common Lisp (SBCL) is a high performance Common Lisp compiler.
    It is open source / free software, with a permissive license. In addition to the
    compiler and runtime system for ANSI Common Lisp, it provides an interactive
    environment including a debugger, a statistical profiler, a code coverage tool,
    and many other extensions.
  doc_url: http://www.sbcl.org/manual/index.html

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
